# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run all unit tests"
  lane :test do
    # The 'scan' action is used for running unit tests
    # You can customize it with additional parameters as needed
    scan(
      # Examples of optional parameters:
      # scheme: "YourSchemeName",  # Define the scheme to use for testing
      # devices: ["iPhone 8", "iPhone 11 Pro"],  # Specify devices to test on
      # clean: true  # Set to 'true' to clean the build before testing
    )
  end

  # You can define other lanes here for different tasks
end

