name: React Native iOS Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install JavaScript Dependencies
        run: yarn install

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Run Expo (iOS)
        run: npx expo run:ios --non-interactive

     
